### ISSUE TITLE
Mobile meny dissappear.

### ISSUE THREAD

**Issue by evildronepilot** [joomdev/jd_boston#1]
Hi, I hope you're well.

On my website, I have a mobile menu disappearing whenever I display ink = category blog.

I tried Duplicating main menu in ofcanvas by publishing module with layout = menu
But under the same types of links that layout changes.... 

Would part of the configuration and missing on what might be wrong?

**Comment by chetanmadaan** [comment]
Not sure what may be causing it. Can you post a link to your webpage where you are having this issue?

Thanks,
Chetan

**Comment by evildronepilot** [comment]
Hi, Thank you for your response.

example 1
https://fpvtown.com/fpv-rc-articles
Under this link I have empty subcategory under articles.

example 2 ( this one is incorrect )
https://fpvtown.com/communities

**Comment by evildronepilot** [comment]
I don't know what is causing this exactly, but I have been playing with a test environment yesterday day.and restore the backup of the database from two weeks back. Now that solve the problem with menu but..... unfortunately I would lose the content :( 
Yet it makes me belive that this is down to a settings not a bug as such.

**Comment by evildronepilot** [comment]
Update: 

I have switched off Asteroid Menu on all the links from the main menu and the problem is now solved. 

If I add Asteroid Menu using Astroid Menu Options under the main menu item in Joomla and do this for only one menu item, the other menu items are not processed correctly and for those, I am losing mobile menu. 
Example: 

![image](https://user-images.githubusercontent.com/46386003/82226010-d8e1cf00-991d-11ea-8234-06bab7008d4f.png)

![image](https://user-images.githubusercontent.com/46386003/82226213-1fcfc480-991e-11ea-9a90-c5830fe69230.png)

![image](https://user-images.githubusercontent.com/46386003/82226324-468dfb00-991e-11ea-8e8c-23839035f7a7.png)

**This is how mobile menu module displayed in offcanvas looks under** 
![image](https://user-images.githubusercontent.com/46386003/82226477-7210e580-991e-11ea-8857-8c7eea79ff8a.png)

**This is How it looks under home page.**
![image](https://user-images.githubusercontent.com/46386003/82226728-c2884300-991e-11ea-83d0-04d755cce502.png)

**Comment by chetanmadaan** [comment]
You are working on the latest dev version of Astroid. is that right?

**Comment by evildronepilot** [comment]
Asteroid 2.3.0

**Comment by evildronepilot** [comment]
Just realised. I posted in the wrong place my template is 
Asteroid_template_zero
sorry

**Comment by chetanmadaan** [comment]
Ok, Why don't you post on our forum at www.joomdev.com/forum and we'll help you there.
